import type { Partner } from "./types";

export const mockPartners: Partner[] = [
  {
    id: "taxi-01",
    name: "아이나비 M 택시",
    category: "택시 호출",
    serviceTypes: ["taxi", "family_mobility"],
    baseFee: 4800,
    deliveryMinutes: 7,
    rating: 4.8,
    location: "전국 주요 도시",
    reservationRequired: false,
    supportsPickup: true,
    supportsTakSong: false,
    notes: "즉시 호출과 예약 호출을 모두 지원합니다.",
    recommendation: "제휴 호출이라 배차 상태와 이동 안내를 함께 확인할 수 있습니다.",
    linkage: ["즉시 호출", "예약 이동", "가족 이동"],
    capabilities: ["출발지/목적지 확인", "배차 상태 안내", "병원 예약 연계"]
  },
  {
    id: "market-01",
    name: "Babelfish 제휴 마켓",
    category: "상품 구매",
    serviceTypes: ["product_purchase", "delivery"],
    baseFee: 3200,
    deliveryMinutes: 28,
    rating: 4.7,
    location: "수도권",
    reservationRequired: false,
    supportsPickup: false,
    supportsTakSong: false,
    notes: "가격과 리뷰를 비교해 협력 구매와 배송을 진행합니다.",
    recommendation: "가격, 리뷰, 배송 가능 여부를 한 번에 비교하기 좋습니다.",
    linkage: ["가격 비교", "리뷰 추천", "배송 확인"],
    capabilities: ["협력사 구매", "상품 비교", "배송 가능 여부 확인"]
  },
  {
    id: "hospital-general-02",
    name: "서울아산병원",
    category: "종합병원",
    serviceTypes: ["hospital_reservation"],
    baseFee: 0,
    deliveryMinutes: 15,
    rating: 5.0,
    location: "서울 송파구",
    reservationRequired: true,
    supportsPickup: false,
    supportsTakSong: false,
    notes: "종합병원 우선 추천 후보입니다.",
    recommendation: "진료과 확인과 예약 가능 여부 확인이 안정적인 제휴 후보입니다.",
    linkage: ["진료 예약", "예약 알림", "아이나비 M 택시 연계"],
    capabilities: ["진료과 추천", "예약 가능 시간 확인", "이동 연계"]
  },
  {
    id: "hospital-general-01",
    name: "서울대병원",
    category: "종합병원",
    serviceTypes: ["hospital_reservation"],
    baseFee: 0,
    deliveryMinutes: 15,
    rating: 4.9,
    location: "서울 종로구",
    reservationRequired: true,
    supportsPickup: false,
    supportsTakSong: false,
    notes: "종합병원 예약 후보로 안내합니다.",
    recommendation: "상급 종합병원 예약 후보로 우선 확인할 수 있습니다.",
    linkage: ["진료 예약", "예약 알림", "아이나비 M 택시 연계"],
    capabilities: ["기존 병원 확인", "진료과 확인", "하루 전/2시간 전 알림"]
  },
  {
    id: "hospital-general-03",
    name: "신촌 세브란스 병원",
    category: "종합병원",
    serviceTypes: ["hospital_reservation"],
    baseFee: 0,
    deliveryMinutes: 15,
    rating: 4.8,
    location: "서울 서대문구",
    reservationRequired: true,
    supportsPickup: false,
    supportsTakSong: false,
    notes: "신촌 권역 종합병원 후보로 안내합니다.",
    recommendation: "종합 진료 예약 후보로 비교 안내할 수 있습니다.",
    linkage: ["진료 예약", "예약 알림", "아이나비 M 택시 연계"],
    capabilities: ["진료과 확인", "예약 가능 시간 확인", "알림 설정"]
  },
  {
    id: "clinic-01",
    name: "샤인빔 클리닉 강남점",
    category: "피부과",
    serviceTypes: ["hospital_reservation"],
    baseFee: 0,
    deliveryMinutes: 12,
    rating: 4.7,
    location: "서울 강남구",
    reservationRequired: true,
    supportsPickup: false,
    supportsTakSong: false,
    notes: "개인 병원 후보로 지역과 일정 기준 확인이 가능합니다.",
    recommendation: "개인 병원 후보로 강남권 피부과 예약 확인이 빠릅니다.",
    linkage: ["피부과 예약", "일정 확인"],
    capabilities: ["위치 기반 추천", "예약 알림", "진료 일정 확인"]
  },
  {
    id: "clinic-02",
    name: "아름다운 피부나라 의원",
    category: "피부과",
    serviceTypes: ["hospital_reservation"],
    baseFee: 0,
    deliveryMinutes: 12,
    rating: 4.6,
    location: "서울 강남구",
    reservationRequired: true,
    supportsPickup: false,
    supportsTakSong: false,
    notes: "개인 피부과 대안 후보입니다.",
    recommendation: "피부 진료 예약 가능 여부를 비교하기 좋습니다.",
    linkage: ["피부과 예약", "일정 확인"],
    capabilities: ["피부 진료 예약", "지역 비교", "예약 확인"]
  },
  {
    id: "oriental-01",
    name: "자생한방병원",
    category: "한방병원",
    serviceTypes: ["hospital_reservation"],
    baseFee: 0,
    deliveryMinutes: 12,
    rating: 4.7,
    location: "전국 주요 지점",
    reservationRequired: true,
    supportsPickup: false,
    supportsTakSong: false,
    notes: "허리, 목 관련 요청에서 한방병원 후보로 안내합니다.",
    recommendation: "통증 관련 증상 기반 추천 후보로 적합합니다.",
    linkage: ["한방 진료 예약", "아이나비 M 택시 연계", "예약 알림"],
    capabilities: ["증상 기반 추천", "예약 가능 시간 확인", "이동 연계"]
  },
  {
    id: "car-01",
    name: "마스터 자동차",
    category: "자동차 정비/검사",
    serviceTypes: ["car_maintenance", "car_inspection"],
    baseFee: 0,
    deliveryMinutes: 20,
    rating: 4.7,
    location: "수도권 주요 지점",
    reservationRequired: true,
    supportsPickup: true,
    supportsTakSong: true,
    notes: "정비, 검사, 탁송 연계를 함께 확인합니다.",
    recommendation: "차량 AS와 검사는 인근 제휴사 중 우선 추천합니다.",
    linkage: ["검사 예약", "정비 예약", "탁송 연결"],
    capabilities: ["검사 일시 확인", "정비 상담", "탁송 기사 연결"]
  },
  {
    id: "car-02",
    name: "공임나라",
    category: "자동차 정비/검사",
    serviceTypes: ["car_maintenance", "car_inspection"],
    baseFee: 0,
    deliveryMinutes: 22,
    rating: 4.6,
    location: "전국 주요 지점",
    reservationRequired: true,
    supportsPickup: true,
    supportsTakSong: true,
    notes: "가격 비교와 정비 예약 후보로 확인합니다.",
    recommendation: "공임과 평판 기준으로 정비소를 비교하기 좋습니다.",
    linkage: ["정비 예약", "가격 비교", "탁송 연결"],
    capabilities: ["오일/타이어/점검", "가격 비교", "예약 가능 시간 확인"]
  },
  {
    id: "car-03",
    name: "블루핸즈",
    category: "자동차 정비/검사",
    serviceTypes: ["car_maintenance", "car_inspection"],
    baseFee: 0,
    deliveryMinutes: 24,
    rating: 4.5,
    location: "전국 주요 지점",
    reservationRequired: true,
    supportsPickup: true,
    supportsTakSong: true,
    notes: "고객 지정 지점이 있으면 해당 지점을 우선 확인합니다.",
    recommendation: "차량 점검과 검사 일정 확인을 함께 진행할 수 있습니다.",
    linkage: ["검사 예약", "정비 예약", "탁송 연결"],
    capabilities: ["검사 예약", "차량 점검", "탁송 가능 여부 확인"]
  },
  {
    id: "accessory-01",
    name: "아이나비 장착 제휴점",
    category: "블랙박스 장착",
    serviceTypes: ["car_accessory_installation"],
    baseFee: 0,
    deliveryMinutes: 20,
    rating: 4.8,
    location: "전국 아이나비 장착 네트워크",
    reservationRequired: true,
    supportsPickup: true,
    supportsTakSong: true,
    notes: "블랙박스는 아이나비 블랙박스 기준으로만 안내합니다.",
    recommendation: "아이나비 블랙박스 장착 가능 여부와 시공 일정을 우선 확인합니다.",
    linkage: ["아이나비 블랙박스 장착", "시공 예약", "탁송 연결"],
    capabilities: ["전후방 블랙박스", "차량 종류 확인", "시공 지역 확인"]
  },
  {
    id: "accessory-02",
    name: "칼트윈 제휴 시공점",
    category: "틴팅 시공",
    serviceTypes: ["car_accessory_installation"],
    baseFee: 0,
    deliveryMinutes: 20,
    rating: 4.8,
    location: "전국 칼트윈 시공 네트워크",
    reservationRequired: true,
    supportsPickup: true,
    supportsTakSong: true,
    notes: "틴팅과 썬팅은 칼트윈 틴팅 필름 기준으로만 안내합니다.",
    recommendation: "칼트윈 틴팅 필름 시공 범위와 예약 가능 시간을 우선 확인합니다.",
    linkage: ["칼트윈 틴팅 필름 시공", "시공 예약", "탁송 연결"],
    capabilities: ["전면 시공", "측후면 시공", "전체 시공", "차량 종류 확인"]
  }
];
