import type { Partner } from "./types";

export const mockPartners: Partner[] = [
  {
    id: "taxi-01",
    name: "아이나비 M 택시",
    category: "택시 호출",
    serviceTypes: ["taxi", "family_mobility"],
    baseFee: 4800,
    deliveryMinutes: 7,
    rating: 4.8,
    location: "전국 주요 도시",
    reservationRequired: false,
    supportsPickup: true,
    supportsTakSong: false,
    notes: "즉시 호출과 예약 호출을 모두 지원합니다.",
    recommendation: "Babelfish 기본 제휴 호출로 배차 상태와 이동 확인까지 연계할 수 있습니다.",
    linkage: ["즉시 호출", "예약 이동", "가족 이동"],
    capabilities: ["출발지/목적지 확인", "배차 상태 안내", "병원 예약 연계"]
  },
  {
    id: "hospital-general-01",
    name: "서울아산병원",
    category: "Babelfish 제휴 병원",
    serviceTypes: ["hospital_reservation"],
    baseFee: 0,
    deliveryMinutes: 15,
    rating: 5.0,
    location: "서울 송파구",
    reservationRequired: true,
    supportsPickup: false,
    supportsTakSong: false,
    notes: "종합병원 예약 후보입니다.",
    recommendation: "진료과와 지역 기준으로 예약 가능 여부를 확인하기 좋습니다.",
    linkage: ["진료 예약", "예약 알림", "아이나비 M 택시 연계"],
    capabilities: ["진료과 확인", "예약 가능 시간 확인", "이동 연계"]
  },
  {
    id: "hospital-general-02",
    name: "서울대병원",
    category: "Babelfish 제휴 병원",
    serviceTypes: ["hospital_reservation"],
    baseFee: 0,
    deliveryMinutes: 15,
    rating: 4.9,
    location: "서울 종로구",
    reservationRequired: true,
    supportsPickup: false,
    supportsTakSong: false,
    notes: "종합병원 예약 후보입니다.",
    recommendation: "진료과와 일정 기준으로 예약 가능 여부를 확인합니다.",
    linkage: ["진료 예약", "예약 알림"],
    capabilities: ["진료과 확인", "예약 가능 시간 확인"]
  },
  {
    id: "clinic-01",
    name: "샤인빔 클리닉 강남점",
    category: "Babelfish 제휴 병원",
    serviceTypes: ["hospital_reservation"],
    baseFee: 0,
    deliveryMinutes: 12,
    rating: 4.7,
    location: "서울 강남구",
    reservationRequired: true,
    supportsPickup: false,
    supportsTakSong: false,
    notes: "개인 병원 예약 후보입니다.",
    recommendation: "지역과 진료 항목 기준으로 빠르게 확인할 수 있습니다.",
    linkage: ["진료 예약", "일정 확인"],
    capabilities: ["위치 기반 추천", "예약 알림"]
  },
  {
    id: "car-01",
    name: "마스터 자동차",
    category: "Babelfish 제휴 자동차 서비스 업체",
    serviceTypes: ["car_maintenance", "car_inspection"],
    baseFee: 0,
    deliveryMinutes: 20,
    rating: 4.7,
    location: "수도권 주요 지역",
    reservationRequired: true,
    supportsPickup: true,
    supportsTakSong: true,
    notes: "정비, 수리, 검사, 탁송 연계를 함께 확인합니다.",
    recommendation: "차량 AS와 정비는 제휴 후보 중 우선 확인합니다.",
    linkage: ["정비 예약", "검사 예약", "탁송 연결"],
    capabilities: ["검사 일시 확인", "정비 상담", "탁송 기사 연결"]
  },
  {
    id: "car-02",
    name: "공임나라",
    category: "Babelfish 제휴 자동차 서비스 업체",
    serviceTypes: ["car_maintenance", "car_inspection"],
    baseFee: 0,
    deliveryMinutes: 22,
    rating: 4.6,
    location: "전국 주요 지역",
    reservationRequired: true,
    supportsPickup: true,
    supportsTakSong: true,
    notes: "공임과 일정 비교가 가능합니다.",
    recommendation: "정비 비용과 일정을 비교하기 좋습니다.",
    linkage: ["정비 예약", "가격 비교", "탁송 연결"],
    capabilities: ["오일/타이어/점검", "가격 비교", "예약 가능 시간 확인"]
  },
  {
    id: "car-03",
    name: "블루핸즈",
    category: "Babelfish 제휴 자동차 서비스 업체",
    serviceTypes: ["car_maintenance", "car_inspection"],
    baseFee: 0,
    deliveryMinutes: 24,
    rating: 4.5,
    location: "전국 주요 지역",
    reservationRequired: true,
    supportsPickup: true,
    supportsTakSong: true,
    notes: "고객 지정 지점이 있으면 해당 지점도 확인합니다.",
    recommendation: "차량 점검과 검사 일정을 함께 확인할 수 있습니다.",
    linkage: ["검사 예약", "정비 예약", "탁송 연결"],
    capabilities: ["검사 예약", "차량 점검", "탁송 가능 여부 확인"]
  },
  {
    id: "accessory-01",
    name: "아이나비 장착 제휴점",
    category: "아이나비 블랙박스 장착",
    serviceTypes: ["car_accessory_installation"],
    baseFee: 0,
    deliveryMinutes: 20,
    rating: 4.8,
    location: "전국 아이나비 장착 네트워크",
    reservationRequired: true,
    supportsPickup: true,
    supportsTakSong: true,
    notes: "블랙박스는 아이나비 블랙박스를 기본으로 안내합니다.",
    recommendation: "아이나비 블랙박스 장착 가능 여부와 시공 일정을 우선 확인합니다.",
    linkage: ["아이나비 블랙박스 장착", "시공 예약", "탁송 연결"],
    capabilities: ["전후방 블랙박스", "차량 종류 확인", "시공 지역 확인"]
  },
  {
    id: "accessory-02",
    name: "칼트윈 제휴 시공점",
    category: "칼트윈 틴팅 필름 시공",
    serviceTypes: ["car_accessory_installation"],
    baseFee: 0,
    deliveryMinutes: 20,
    rating: 4.8,
    location: "전국 칼트윈 시공 네트워크",
    reservationRequired: true,
    supportsPickup: true,
    supportsTakSong: true,
    notes: "틴팅과 썬팅은 칼트윈 틴팅 필름을 기본으로 안내합니다.",
    recommendation: "칼트윈 틴팅 필름 시공 범위와 예약 가능 시간을 우선 확인합니다.",
    linkage: ["칼트윈 틴팅 필름 시공", "시공 예약", "탁송 연결"],
    capabilities: ["전면 시공", "측후면 시공", "전체 시공", "차량 종류 확인"]
  },
  {
    id: "market-01",
    name: "Babelfish 제휴 협력사",
    category: "상품 구매",
    serviceTypes: ["product_purchase", "delivery"],
    baseFee: 3200,
    deliveryMinutes: 28,
    rating: 4.7,
    location: "수도권",
    reservationRequired: false,
    supportsPickup: false,
    supportsTakSong: false,
    notes: "가격과 리뷰를 비교해 제휴 구매와 배송을 진행합니다.",
    recommendation: "가격, 리뷰, 배송 가능 여부를 한 번에 비교하기 좋습니다.",
    linkage: ["가격 비교", "리뷰 추천", "배송 확인"],
    capabilities: ["협력사 구매", "상품 비교", "배송 가능 여부 확인"]
  }
];
